Add backlight information
Eeems-Org/remarkable.guide pull request #78
Opened 2024-10-06 18:32 UTC by Jayy001

This PR adds information for the ReMarkable Paper Pro device backlight.

2024-10-06 18:52 UTC, Eeems requested changes
I think this information should live in the  `src/devel/device/display.rst` page instead and just talk about the programmatic side of things as well as link to https://github.com/torvalds/linux/blob/master/Documentation/ABI/stable/sysfs-class-backlight for documentation on the sysfs interface.

Also, could you quickly run `make spelling` and fix misspelled words, or add them alphabetically to `src/spelling_wordlist.txt` if needed.

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +The ReMarkable Paper Pro has a backlight that can be adjusted to make the screen easier to read in different lighting conditions.
```suggestion
The reMarkable Paper Pro has a backlight that can be adjusted to make the screen easier to read in different lighting conditions.
```

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +Setting the brightness too high may cause the device to overheat and potentially damage the screen.
```suggestion
Setting the brightness outside of the range you can select in xochitl will make the battery drain faster, and may have unintended side effects that could damage the device.
```
Since this is conjecture, we shouldn't commit to saying what will happen, and instead just say we don't know what will happen.

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +  echo 2047 > /sys/class/backlight/backlight/brightness
```suggestion
  echo 1734 > /sys/class/backlight/backlight/brightness
```
Let's avoid having people default to using the max value to test things when we just above say we don't recommend it.

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +============================
```suggestion
=============================
Changing the Device Backlight
=============================
```

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +============================
```suggestion
Adjusting in the UI
===================
```

This section should point to the official documentation on the quick settings: https://support.remarkable.com/s/article/Quick-settings instead of re-documenting how to open them.

2024-10-06 18:52 UTC, Eeems commented on src/guide/config/backlight.rst
> +============================
```suggestion
Adjusting programmatically
==========================
```

2024-10-08 04:33 UTC, Eeems commented
@Jayy001 poke

2024-10-08 12:38 UTC, knox-dawson commented on src/guide/config/backlight.rst
> +  echo 2047 > /sys/class/backlight/backlight/brightness
echo <num> /sys/class/backlight/rm_frontlight/brightness

2024-10-08 13:26 UTC, Jayy001 commented on src/guide/config/backlight.rst
> +============================
The official documentation doesn't provide the numeric values, I think this is quite helpful to have.

2024-10-08 13:57 UTC, Eeems commented on src/guide/config/backlight.rst
> +============================
Yes, but the numeric values are more important for the programattic section, and not for the UI, and as for the UI we should still be pointing to the official support documentation wherever possible.

2024-10-12 21:32 UTC, Eeems commented
@Jayy001 poke again?

2024-10-13 17:38 UTC, Jayy001 commented on src/guide/config/backlight.rst
> +============================
I've pointed to the main documentation as well as adding the values

2024-10-13 17:39 UTC, Jayy001 commented
I've moved the contents to a new file and updated some of the text, ready for a review

2024-10-13 18:03 UTC, Eeems commented on src/devel/device/display.rst
> +============================
```suggestion
Adjusting in the UI
===================
```

2024-10-13 18:03 UTC, Eeems commented on src/devel/device/display.rst
> +=========================
```suggestion
Adjusting programmatically
==========================
```

2024-10-13 18:35 UTC, Eeems approved these changes

2024-10-13 18:35 UTC, merged