docs: how to load module for bluetooth
Eeems-Org/remarkable.guide pull request #79
Opened 2024-10-07 05:10 UTC by Lewiscowles1986

just a stub page based on discord. Tested on my remarkable paper pro, it worked, I liked it.

2024-10-07 05:36 UTC, Eeems requested changes
This will need to specify that this is only for the reMarkable Paper Pro. It should also link to external documentation for the kernel module and bluetoothctl so that users can continue to red up on it there.

2024-10-07 05:36 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +====
```suggestion
=========
Bluetooth
=========
```

2024-10-07 05:36 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +------------------------
```suggestion
Enabling bluetooth
------------------
```

2024-10-07 05:36 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +    SupportedSecondaryChannels: Coded
```suggestion
.. code-block:: shell

  modprobe btnxpuart
  bluetoothctl show
```

2024-10-07 05:38 UTC, Eeems requested changes

2024-10-07 05:38 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +By default Bluetooth is not configured to work. But the module exists, the kernel is built to use it.
```suggestion
By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
```
To keep consistent with lack of capitalization elsewhere in the document

2024-10-08 04:08 UTC, Lewiscowles1986 commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
How about this edit:

```suggestion
This article is about the <strong>ReMarkable Paper Pro</strong>.

By default, bluetooth on the rMPP is not configured to work. A Kernel module does exist, and the kernel is built to use it.
```

2024-10-08 04:23 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
I should add some guidance to the readme, but we use the full name instead of rM1/rM2/rMPP throughout the guide. It's also styalized as reMarkable and not ReMarkable.

2024-10-08 04:26 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
It might just be worth saying something like:

> The reMarkable 1 and 2 do not have bluetooth. The reMarkable Paper Pro does have bluetooth hardware, but the driver is not loaded by default.

2024-10-08 04:28 UTC, Eeems commented
For the external links you can throw at the bottom for users to get more information, the [bluetooth archwiki article](https://wiki.archlinux.org/title/Bluetooth) would probably be good. Here is what I can find on the kernel module: https://community.nxp.com/t5/i-MX-Processors-Knowledge-Base/Bluetooth-NXP-UART-Driver-Linux-BSP-6-1-22-btnxpuart/ta-p/1708588

2024-10-09 20:51 UTC, Lewiscowles1986 commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
updated.

2024-10-09 20:52 UTC, Lewiscowles1986 commented
> For the external links you can throw at the bottom for users to get more information, the [bluetooth archwiki article](https://wiki.archlinux.org/title/Bluetooth) would probably be good. Here is what I can find on the kernel module: https://community.nxp.com/t5/i-MX-Processors-Knowledge-Base/Bluetooth-NXP-UART-Driver-Linux-BSP-6-1-22-btnxpuart/ta-p/1708588

Can you tell me a little more about what you try to strive for with links. I can blindly copy-pasta the examples you gave, but I think we both want this to be useful, so understanding what you think works might help me address the needs better.

2024-10-10 00:07 UTC, Eeems commented
> Can you tell me a little more about what you try to strive for with links. I can blindly copy-pasta the examples you gave, but I think we both want this to be useful, so understanding what you think works might help me address the needs better.

https://remarkable.guide/devel/device/upgrade_engine.html#external-links would be an example of what I'm looking for. It directs users to places with further reading to things that apply to what has been discussed in the article, with a short description that provides some context as to why it's relevant. This can be external tools that the reader could find useful, external documentation for something that would be a good reference, external documentation for something unrelated to rM that would have concepts that would be useful here, etc.

2024-10-10 00:08 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
Did you forget to push a commit? I'm still seeing the old text here.

2024-10-10 06:12 UTC, Lewiscowles1986 commented on src/devel/device/bluetooth.rst
> +By default bluetooth is not configured to work. But the module exists, the kernel is built to use it.
Ah sorry I updated the suggestion 😂 .

One of my pet peeves is folks being too quick to action, when discussing. I guess that conversely means I can be slow to action.

2024-10-10 06:30 UTC, Lewiscowles1986 commented
Changes made, both discussed and something I hope will make the page less of a stub.

2024-10-12 21:56 UTC, Eeems requested changes

2024-10-12 21:56 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +   https://wiki.archlinux.org/title/Bluetooth#Configuration
```suggestion
- ArchWiki article on Bluetooth
   https://wiki.archlinux.org/title/Bluetooth
```

Having three links to the same page isn't something I'd like to add, and we do try to stylize things the way they are intended by the authors.

2024-10-12 21:56 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +   https://www.bluez.org/
```suggestion
- Documentation for bluetoothctl and related commands
   https://man.archlinux.org/listing/extra/bluez-utils/
```
This isn't really linking someone to something that immediately has useful information, they instead have to do a bunch of digging to find any useful documentation on bluetoothctl. I would much rather link to hosted documentation for bluetoothctl and other commands bluez provides.

2024-10-12 21:56 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +  Connection successful
I'm not a big fan of including command output like this in the article. Some users will read this and have some difficulty determining what commands we are saying to run. 

```suggestion
.. code-block:: shell

  bluetoothctl

 This will drop you into an interactive prompt for running bluetoothctl commands.
 
 .. code-block:: shell
   power on
   scan on
   # Wait for the mac address for the device you are interested to show up
   pair <mac-address>
   # You will be prompted to enter a PIN code for the device
   connect <mac-address>
   trust <mac-address>
```

I did some digging and there seems to be no good way to scan without actually running the interact prompt, which is rather odd.

2024-10-12 21:56 UTC, Eeems commented on src/devel/device/bluetooth.rst
> +    </div>
```suggestion
:raw-html:`<div class="warning">⚠️ FIXME. ⚠️`

This page is just a stub that needs to be completed. You can `open a PR on the repo <https://github.com/Eeems-Org/remarkable.guide>`_ to add more content to the page.
:raw-html:`</div>`
```

The entire site is from individual user experimentation, and the device documentation itself is meant to provide lower level information that still needs to be gathered. If you are saying that this page isn't done, then the stub notice would be the correct thing to add here: https://github.com/Eeems-Org/remarkable.guide?tab=readme-ov-file#how-do-i-mark-a-page-as-a-stub-that-needs-further-content-written

2024-10-13 18:41 UTC, Eeems approved these changes

2024-10-13 18:46 UTC, merged